using System.Collections.ObjectModel;
using System.Text.Json.Serialization;

namespace AroMotion.App.Models;

public sealed class Motion3DSegment
{
    public Guid Id { get; init; } = Guid.NewGuid();
    public long StartMs { get; set; }
    public long EndMs { get; set; }
    public string Preset { get; set; } = "Focus";
    public double RotateX { get; set; }
    public double RotateY { get; set; }
    public double RotateZ { get; set; }
    public double Depth { get; set; }
    public double PanX { get; set; }
    public double PanY { get; set; }
    public double Perspective { get; set; } = 1.0;
    public double Speed { get; set; } = 1.0;
    public double Intensity { get; set; } = 1.0;
    public long HoldMs { get; set; } = 650;
    public string Easing { get; set; } = "cubic-in-out";
    public bool Shadow { get; set; } = true;
    public bool Reflection { get; set; }
    public bool AutoGenerated { get; set; }
    public bool Enabled { get; set; } = true;
}

public sealed class CursorEffectProfile
{
    public string Style { get; set; } = "AROMOTION White";
    public bool ReplaceOriginalCursor { get; set; } = true;
    public bool HideCursor { get; set; }
    public string? CustomCursorPath { get; set; }
    public string Color { get; set; } = "#FFFFFF";
    public bool Shadow { get; set; } = true;
    public double Opacity { get; set; } = 1.0;
    public double Size { get; set; } = 1.0;
    public string ClickRingStyle { get; set; } = "Pulse";
    public string LeftClickColor { get; set; } = "#7C5CFF";
    public string RightClickColor { get; set; } = "#FF5D8F";
    public int ClickAnimationMs { get; set; } = 420;
    public string? ClickSoundPath { get; set; }
    public bool ClickSoundEnabled { get; set; } = true;
    public double MotionBlur { get; set; } = 0.25;
    public bool SmoothCursor { get; set; } = true;
    public double Smoothing { get; set; } = 0.68;
    public bool CursorFollowZoom { get; set; }
}

public sealed class SpotlightEffect
{
    public Guid Id { get; init; } = Guid.NewGuid();
    public long StartMs { get; set; }
    public long EndMs { get; set; }
    public string Shape { get; set; } = "Circle";
    public int X { get; set; }
    public int Y { get; set; }
    public int Width { get; set; } = 320;
    public int Height { get; set; } = 220;
    public double Darkness { get; set; } = 0.68;
    public double Feather { get; set; } = 28;
    public bool FollowCursor { get; set; }
    public bool Enabled { get; set; } = true;
}

public sealed class BlurEffect
{
    public Guid Id { get; init; } = Guid.NewGuid();
    public long StartMs { get; set; }
    public long EndMs { get; set; }
    public int X { get; set; }
    public int Y { get; set; }
    public int Width { get; set; } = 360;
    public int Height { get; set; } = 120;
    public double Intensity { get; set; } = 18;
    public double Feather { get; set; } = 8;
    public bool TrackCursor { get; set; }
    public bool Enabled { get; set; } = true;
}

public sealed class MotionProjectState
{
    public int Version { get; set; } = 1;
    public string? SourceVideo { get; set; }
    public string? EventsPath { get; set; }
    public int CanvasWidth { get; set; } = 1920;
    public int CanvasHeight { get; set; } = 1080;
    public ObservableCollection<ZoomSegment> Zooms { get; set; } = new();
    public ObservableCollection<Motion3DSegment> Motions3D { get; set; } = new();
    public ObservableCollection<SpotlightEffect> Spotlights { get; set; } = new();
    public ObservableCollection<BlurEffect> Blurs { get; set; } = new();
    public CursorEffectProfile Cursor { get; set; } = new();

    [JsonIgnore]
    public bool IsDirty { get; set; }
}
