using System.Collections.ObjectModel;
using System.Text.Json;
using AroMotion.App.Models;

namespace AroMotion.App.Services;

public sealed class MotionTimelineService
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    public MotionProjectState Project { get; private set; } = new();

    public async Task<MotionProjectState> OpenAsync(string projectDirectory)
    {
        var statePath = Path.Combine(projectDirectory, "motion-project.json");
        var sourceVideo = ResolveFirstExisting(projectDirectory, "screen_master.mkv", "master.mkv", "recording_with_audio.mkv");
        var eventsPath = ResolveFirstExisting(projectDirectory, "events.jsonl", "capture-events.jsonl", "mouse_events.jsonl", "mouse_events.csv");

        if (File.Exists(statePath))
        {
            try
            {
                var json = await File.ReadAllTextAsync(statePath);
                Project = JsonSerializer.Deserialize<MotionProjectState>(json, JsonOptions) ?? new MotionProjectState();
            }
            catch { Project = new MotionProjectState(); }
        }
        else Project = new MotionProjectState();

        Project.SourceVideo ??= sourceVideo;
        Project.EventsPath ??= eventsPath;
        Project.Zooms ??= new ObservableCollection<ZoomSegment>();
        Project.Motions3D ??= new ObservableCollection<Motion3DSegment>();
        Project.Spotlights ??= new ObservableCollection<SpotlightEffect>();
        Project.Blurs ??= new ObservableCollection<BlurEffect>();
        Project.Cursor ??= new CursorEffectProfile();
        foreach (var m in Project.Motions3D) m.Keyframes ??= new ObservableCollection<Motion3DKeyframe>();
        Project.IsDirty = false;
        return Project;
    }

    public async Task SaveAsync(string projectDirectory)
    {
        Directory.CreateDirectory(projectDirectory);
        var statePath = Path.Combine(projectDirectory, "motion-project.json");
        var json = JsonSerializer.Serialize(Project, JsonOptions);
        await File.WriteAllTextAsync(statePath, json);
        Project.IsDirty = false;
    }

    public void ReplaceAutoZooms(IEnumerable<ZoomSegment> segments)
    {
        var manual = Project.Zooms.Where(x => x.Source == "manual").Select(x => x.Clone()).ToList();
        Project.Zooms.Clear();
        foreach (var item in segments.OrderBy(x => x.StartMs)) Project.Zooms.Add(item);
        foreach (var item in manual.OrderBy(x => x.StartMs)) Project.Zooms.Add(item);
        SortZooms(); Touch();
    }

    public ZoomSegment AddManualZoom(long atMs, int x, int y, double scale = 1.75)
    {
        var segment = new AutoZoomGenerator().CreateManual(atMs, x, y, scale);
        Project.Zooms.Add(segment); SortZooms(); Touch(); return segment;
    }

    public void MoveZoom(ZoomSegment segment, long newStartMs)
    {
        var duration = Math.Max(1, segment.EndMs - segment.StartMs);
        segment.StartMs = Math.Max(0, newStartMs); segment.EndMs = segment.StartMs + duration;
        SortZooms(); Touch();
    }

    public void ResizeZoom(ZoomSegment segment, long newStartMs, long newEndMs)
    {
        segment.StartMs = Math.Max(0, Math.Min(newStartMs, newEndMs - 1));
        segment.EndMs = Math.Max(segment.StartMs + 1, newEndMs);
        var duration = segment.EndMs - segment.StartMs;
        segment.ZoomInMs = Math.Min(segment.ZoomInMs, duration);
        segment.ZoomOutMs = Math.Min(segment.ZoomOutMs, duration);
        segment.HoldMs = Math.Max(0, duration - segment.ZoomInMs - segment.ZoomOutMs);
        SortZooms(); Touch();
    }

    public void SetZoomFocus(ZoomSegment segment, int x, int y)
    {
        segment.FocusX = x; segment.FocusY = y; segment.SmartFrame = false;
        segment.FrameX = segment.FrameY = segment.FrameWidth = segment.FrameHeight = null;
        Touch();
    }

    public void DeleteZoom(ZoomSegment segment) { Project.Zooms.Remove(segment); Touch(); }

    public Motion3DSegment Add3D(long startMs, long endMs, string preset)
    {
        var segment = MotionPresetService.CreatePreset(preset, startMs, endMs);
        Project.Motions3D.Add(segment); Touch(); return segment;
    }

    public IReadOnlyList<Motion3DSegment> Generate3DFromZooms(string preset = "Focus")
    {
        var manual = Project.Motions3D.Where(x => !x.AutoGenerated).ToList();
        Project.Motions3D.Clear();
        foreach (var z in Project.Zooms.Where(x => x.Enabled).OrderBy(x => x.StartMs))
        {
            var motion = MotionPresetService.CreatePreset(preset, z.StartMs, z.EndMs);
            motion.AutoGenerated = true;
            // Make the 3D direction react to the focus point, so clicks on the left
            // tilt differently from clicks on the right rather than repeating one canned move.
            var nx = (z.FocusX / (double)Math.Max(1, Project.CanvasWidth)) - .5;
            var ny = (z.FocusY / (double)Math.Max(1, Project.CanvasHeight)) - .5;
            motion.RotateY += nx * 14;
            motion.RotateX += -ny * 10;
            motion.PanX += -nx * 18;
            motion.PanY += -ny * 14;
            RegenerateKeyframes(motion);
            Project.Motions3D.Add(motion);
        }
        foreach (var m in manual) Project.Motions3D.Add(m);
        Touch();
        return Project.Motions3D.ToList();
    }

    public Motion3DKeyframe Add3DKeyframe(Motion3DSegment segment, long timeMs)
    {
        timeMs = Math.Clamp(timeMs, segment.StartMs, segment.EndMs);
        var key = new Motion3DKeyframe
        {
            TimeMs = timeMs,
            RotateX = segment.RotateX,
            RotateY = segment.RotateY,
            RotateZ = segment.RotateZ,
            Depth = segment.Depth,
            PanX = segment.PanX,
            PanY = segment.PanY,
            Perspective = segment.Perspective,
            Easing = segment.Easing
        };
        segment.Keyframes.Add(key);
        SortKeyframes(segment); Touch(); return key;
    }

    public void RegenerateKeyframes(Motion3DSegment segment)
    {
        segment.Keyframes.Clear();
        var duration = Math.Max(1, segment.EndMs - segment.StartMs);
        var inTime = segment.StartMs + Math.Min(420, duration / 3);
        var outTime = segment.EndMs - Math.Min(420, duration / 3);
        segment.Keyframes.Add(new Motion3DKeyframe { TimeMs = segment.StartMs, Easing = segment.Easing });
        segment.Keyframes.Add(MotionPresetService.Peak(segment, inTime));
        if (outTime > inTime + 60) segment.Keyframes.Add(MotionPresetService.Peak(segment, outTime));
        segment.Keyframes.Add(new Motion3DKeyframe { TimeMs = segment.EndMs, Easing = segment.Easing });
        SortKeyframes(segment); Touch();
    }

    public void Delete3D(Motion3DSegment segment) { Project.Motions3D.Remove(segment); Touch(); }

    public SpotlightEffect AddSpotlight(long startMs, long endMs, int x, int y, string shape = "Circle")
    {
        var effect = new SpotlightEffect { StartMs = startMs, EndMs = endMs, X = x, Y = y, Shape = shape };
        Project.Spotlights.Add(effect); Touch(); return effect;
    }

    public BlurEffect AddBlur(long startMs, long endMs, int x, int y)
    {
        var effect = new BlurEffect { StartMs = startMs, EndMs = endMs, X = x, Y = y };
        Project.Blurs.Add(effect); Touch(); return effect;
    }

    public void DeleteSpotlight(SpotlightEffect effect) { Project.Spotlights.Remove(effect); Touch(); }
    public void DeleteBlur(BlurEffect effect) { Project.Blurs.Remove(effect); Touch(); }
    public void Touch() => Project.IsDirty = true;

    private void SortZooms()
    {
        var sorted = Project.Zooms.OrderBy(x => x.StartMs).ThenBy(x => x.EndMs).ToList();
        Project.Zooms.Clear(); foreach (var item in sorted) Project.Zooms.Add(item);
    }

    private static void SortKeyframes(Motion3DSegment segment)
    {
        var sorted = segment.Keyframes.OrderBy(k => k.TimeMs).ToList();
        segment.Keyframes.Clear(); foreach (var key in sorted) segment.Keyframes.Add(key);
    }

    private static string? ResolveFirstExisting(string directory, params string[] names)
    {
        foreach (var name in names) { var path = Path.Combine(directory, name); if (File.Exists(path)) return path; }
        return null;
    }
}
