Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
[System.Windows.Forms.Application]::EnableVisualStyles()

$root=$PSScriptRoot
$ffmpeg=Join-Path $root 'tools\ffmpeg\ffmpeg.exe'
if(-not(Test-Path $ffmpeg)){[System.Windows.Forms.MessageBox]::Show('Run START-NOW.cmd first.','AROMOTION Studio',[System.Windows.Forms.MessageBoxButtons]::OK,[System.Windows.Forms.MessageBoxIcon]::Error)|Out-Null;exit 1}
$script:p=$null;$script:lastFile=$null
$videos=[Environment]::GetFolderPath('MyVideos');if([string]::IsNullOrWhiteSpace($videos)){$videos=[Environment]::GetFolderPath('MyDocuments')}
$default=Join-Path $videos 'AROMOTION Projects';New-Item -ItemType Directory -Force -Path $default|Out-Null

$f=New-Object System.Windows.Forms.Form;$f.Text='AROMOTION Studio - Lossless Recorder M0';$f.StartPosition='CenterScreen';$f.ClientSize=New-Object System.Drawing.Size(760,455);$f.BackColor=[Drawing.Color]::FromArgb(16,18,22);$f.ForeColor=[Drawing.Color]::White;$f.Font=New-Object Drawing.Font('Segoe UI',10)
function L($t,$x,$y,$s=10,$b=$false){$o=New-Object Windows.Forms.Label;$o.Text=$t;$o.AutoSize=$true;$o.Location=New-Object Drawing.Point($x,$y);if($b){$o.Font=New-Object Drawing.Font('Segoe UI',$s,[Drawing.FontStyle]::Bold)}elseif($s-ne10){$o.Font=New-Object Drawing.Font('Segoe UI',$s)};$f.Controls.Add($o);$o}
L 'AROMOTION' 28 20 22 $true|Out-Null;$sub=L 'Pixel-perfect lossless Windows screen recorder - immediate build' 31 61;$sub.ForeColor=[Drawing.Color]::FromArgb(165,174,190);$st=L 'READY' 665 31 10 $true;$st.ForeColor=[Drawing.Color]::FromArgb(130,220,165)
L 'Project folder' 31 102|Out-Null;$folder=New-Object Windows.Forms.TextBox;$folder.Text=$default;$folder.Location=New-Object Drawing.Point(34,127);$folder.Size=New-Object Drawing.Size(570,28);$f.Controls.Add($folder)
$browse=New-Object Windows.Forms.Button;$browse.Text='Browse...';$browse.Location=New-Object Drawing.Point(616,125);$browse.Size=New-Object Drawing.Size(105,31);$browse.Add_Click({$d=New-Object Windows.Forms.FolderBrowserDialog;$d.SelectedPath=$folder.Text;if($d.ShowDialog()-eq[Windows.Forms.DialogResult]::OK){$folder.Text=$d.SelectedPath}});$f.Controls.Add($browse)
L 'Quality' 31 177|Out-Null;$quality=New-Object Windows.Forms.ComboBox;$quality.DropDownStyle='DropDownList';[void]$quality.Items.Add('FFV1 - mathematically lossless (recommended)');[void]$quality.Items.Add('H.264 RGB CRF 0 - lossless RGB');$quality.SelectedIndex=0;$quality.Location=New-Object Drawing.Point(34,202);$quality.Size=New-Object Drawing.Size(445,30);$f.Controls.Add($quality)
L 'FPS' 505 177|Out-Null;$fps=New-Object Windows.Forms.ComboBox;$fps.DropDownStyle='DropDownList';[void]$fps.Items.Add('30');[void]$fps.Items.Add('60');$fps.SelectedIndex=1;$fps.Location=New-Object Drawing.Point(508,202);$fps.Size=New-Object Drawing.Size(82,30);$f.Controls.Add($fps)
$cursor=New-Object Windows.Forms.CheckBox;$cursor.Text='Record visible mouse cursor';$cursor.Checked=$true;$cursor.AutoSize=$true;$cursor.Location=New-Object Drawing.Point(34,250);$f.Controls.Add($cursor)
$rec=New-Object Windows.Forms.Button;$rec.Text='●  RECORD LOSSLESS';$rec.Font=New-Object Drawing.Font('Segoe UI',12,[Drawing.FontStyle]::Bold);$rec.Location=New-Object Drawing.Point(34,295);$rec.Size=New-Object Drawing.Size(325,58);$rec.FlatStyle='Flat';$rec.BackColor=[Drawing.Color]::FromArgb(210,62,74);$rec.ForeColor=[Drawing.Color]::White;$f.Controls.Add($rec)
$stop=New-Object Windows.Forms.Button;$stop.Text='■  STOP & SAVE';$stop.Font=New-Object Drawing.Font('Segoe UI',12,[Drawing.FontStyle]::Bold);$stop.Location=New-Object Drawing.Point(396,295);$stop.Size=New-Object Drawing.Size(325,58);$stop.FlatStyle='Flat';$stop.Enabled=$false;$f.Controls.Add($stop)
$n=L 'M0 is the lossless capture foundation. Audio + auto zoom + smooth separate cursor + FocuSee-style 3D motion + timeline editing are the next milestones.' 34 385 9;$n.ForeColor=[Drawing.Color]::FromArgb(155,164,180);$n.MaximumSize=New-Object Drawing.Size(680,45)

function UI([bool]$r){$rec.Enabled=-not$r;$stop.Enabled=$r;$folder.Enabled=-not$r;$browse.Enabled=-not$r;$quality.Enabled=-not$r;$fps.Enabled=-not$r;$cursor.Enabled=-not$r;if($r){$st.Text='● RECORDING';$st.ForeColor=[Drawing.Color]::FromArgb(255,95,105)}else{$st.Text='READY';$st.ForeColor=[Drawing.Color]::FromArgb(130,220,165)}}
function SaveStop{if($null-ne$script:p){try{if(-not$script:p.HasExited){$script:p.StandardInput.WriteLine('q');$script:p.StandardInput.Flush();if(-not$script:p.WaitForExit(8000)){$script:p.Kill();$script:p.WaitForExit()}}}catch{};try{$script:p.Dispose()}catch{};$script:p=$null};UI $false;$st.Text='SAVED';if($script:lastFile-and(Test-Path $script:lastFile)){$r=[Windows.Forms.MessageBox]::Show("Lossless master saved:`r`n$script:lastFile`r`n`r`nOpen folder?",'AROMOTION Studio',[Windows.Forms.MessageBoxButtons]::YesNo,[Windows.Forms.MessageBoxIcon]::Information);if($r-eq[Windows.Forms.DialogResult]::Yes){Start-Process explorer.exe -ArgumentList "/select,`"$script:lastFile`""}}}

$rec.Add_Click({try{$base=$folder.Text.Trim();if([string]::IsNullOrWhiteSpace($base)){throw 'Choose a project folder.'};New-Item -ItemType Directory -Force -Path $base|Out-Null;$session=Join-Path $base (Get-Date -Format 'yyyy-MM-dd_HHmmss');New-Item -ItemType Directory -Force -Path $session|Out-Null;$script:lastFile=Join-Path $session 'master.mkv';$rate=$fps.SelectedItem.ToString();$mouse=if($cursor.Checked){'1'}else{'0'};$codec=if($quality.SelectedIndex-eq0){'-c:v ffv1 -level 3 -coder 1 -g 1'}else{'-c:v libx264rgb -crf 0 -preset ultrafast'};$args='-hide_banner -y -f gdigrab -framerate '+$rate+' -draw_mouse '+$mouse+' -i desktop '+$codec+' -f matroska "'+$script:lastFile+'"';$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$ffmpeg;$psi.Arguments=$args;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardInput=$true;$script:p=New-Object Diagnostics.Process;$script:p.StartInfo=$psi;if(-not$script:p.Start()){throw 'Could not start recording engine.'};Start-Sleep -Milliseconds 400;if($script:p.HasExited){throw "Recording engine stopped immediately. Exit code $($script:p.ExitCode)."};UI $true}catch{if($null-ne$script:p){try{$script:p.Dispose()}catch{};$script:p=$null};[Windows.Forms.MessageBox]::Show($_.Exception.Message,'AROMOTION recorder error',[Windows.Forms.MessageBoxButtons]::OK,[Windows.Forms.MessageBoxIcon]::Error)|Out-Null}})
$stop.Add_Click({SaveStop})
$f.Add_FormClosing({if($null-ne$script:p-and-not$script:p.HasExited){$r=[Windows.Forms.MessageBox]::Show('Stop and save the current recording before closing?','AROMOTION Studio',[Windows.Forms.MessageBoxButtons]::YesNo,[Windows.Forms.MessageBoxIcon]::Question);if($r-eq[Windows.Forms.DialogResult]::Yes){SaveStop}else{$_.Cancel=$true}}})
[void]$f.ShowDialog()
